
dir = [
    'N', 'NO', 'NORTE', 'NORTH',
    'E', 'EA', 'EAST', 'ESTE',
    'S', 'SO', 'SOUTH', 'SUR',
    'W', 'WE', 'WEST', 'OESTE',
    'NE', 'NORTHEAST', 'NORESTE',
    'SE', 'SOUTHEAST', 'SURESTE',
    'NW', 'NORTHWEST', 'NOROESTE',
    'SOUTHWEST', 'SUROESTE', 'SW'
    ]

unit = ['APARTMENT', 'APT', 'BASEMENT', 'BLDG', 'BSMT', 'BUILDING', 'DEPARTMENT', 'DEPT', 'FL', 'FLOOR', 'FRNT',
        'FRONT', 'HANGER', 'HNGR', 'KEY', 'KEY', 'LBBY', 'LOBBY', 'LOT', 'LOT', 'LOWER', 'LOWR', 'OFC', 'OFFICE',
        'PENTHOUSE', 'PH', 'PIER', 'PIER', 'REAR', 'REAR', 'RM', 'ROOM', 'SIDE', 'SIDE', 'SLIP', 'SLIP', 'SPACE',
        'SPC', 'STE', 'STOP', 'STOP', 'SUITE', 'TRAILER', 'TRLR', 'UNIT', 'UNIT', 'UPPER', 'UPPR']

typ = ['ALLEE', 'ALLEY', 'ALLY', 'ALY', 'ANEX', 'ANNEX', 'ANNX', 'ANX', 'ARC', 'ARCADE', 'AV', 'AVE', 'AVEN', 'AVENU',
       'AVENUE', 'AVN', 'AVNUE', 'BAYOO', 'BAYOU', 'BCH', 'BEACH', 'BEND', 'BG', 'BGS', 'BLF', 'BLFS', 'BLUF', 'BLUFF',
       'BLUFFS', 'BLVD', 'BND', 'BOT', 'BOTTM', 'BOTTOM', 'BOUL', 'BOULEVARD', 'BOULV', 'BR', 'BRANCH', 'BRDGE', 'BRG',
       'BRIDGE', 'BRK', 'BRKS', 'BRNCH', 'BROOK', 'BROOKS', 'BTM', 'BURG', 'BURGS', 'BYP', 'BYPA', 'BYPAS', 'BYPASS',
       'BYPS', 'BYU', 'CAMP', 'CANYN', 'CANYON', 'CAPE', 'CAUSEWAY', 'CAUSWA', 'CEN', 'CENT', 'CENTER', 'CENTERS',
       'CENTR', 'CENTRE', 'CIR', 'CIRC', 'CIRCL', 'CIRCLE', 'CIRCLES', 'CIRS', 'CLB', 'CLF', 'CLFS', 'CLIFF', 'CLIFFS',
       'CLUB', 'CMN', 'CMNS', 'CMP', 'CNTER', 'CNTR', 'CNYN', 'COMMON', 'COMMONS', 'COR', 'CORNER', 'CORNERS', 'CORS',
       'COURSE', 'COURT', 'COURTS', 'COVE', 'COVES', 'CP', 'CPE', 'CRCL', 'CRCLE', 'CREEK', 'CRES', 'CRESCENT', 'CREST',
       'CRK', 'CROSSING', 'CROSSROAD', 'CROSSROADS', 'CRSE', 'CRSENT', 'CRSNT', 'CRSSNG', 'CRST', 'CSWY', 'CT', 'CTR',
       'CTRS', 'CTS', 'CURV', 'CURVE', 'CV', 'CVS', 'CYN', 'DALE', 'DAM', 'DIV', 'DIVIDE', 'DL', 'DM', 'DR', 'DRIV',
       'DRIVE', 'DRIVES', 'DRS', 'DRV', 'DV', 'DVD', 'EST', 'ESTATE', 'ESTATES', 'ESTS', 'EXP', 'EXPR', 'EXPRESS',
       'EXPRESSWAY', 'EXPW', 'EXPY', 'EXT', 'EXTENSION', 'EXTENSIONS', 'EXTN', 'EXTNSN', 'EXTS', 'FALL', 'FALLS',
       'FERRY', 'FIELD', 'FIELDS', 'FLAT', 'FLATS', 'FLD', 'FLDS', 'FLS', 'FLT', 'FLTS', 'FORD', 'FORDS', 'FOREST',
       'FORESTS', 'FORG', 'FORGE', 'FORGES', 'FORK', 'FORKS', 'FORT', 'FRD', 'FRDS', 'FREEWAY', 'FREEWY', 'FRG', 'FRGS',
       'FRK', 'FRKS', 'FRRY', 'FRST', 'FRT', 'FRWAY', 'FRWY', 'FRY', 'FT', 'FWY', 'GARDEN', 'GARDENS', 'GARDN',
       'GATEWAY', 'GATEWY', 'GATWAY', 'GDN', 'GDNS', 'GLEN', 'GLENS', 'GLN', 'GLNS', 'GRDEN', 'GRDN', 'GRDNS', 'GREEN',
       'GREENS', 'GRN', 'GRNS', 'GROV', 'GROVE', 'GROVES', 'GRV', 'GRVS', 'GTWAY', 'GTWY', 'HARB', 'HARBOR', 'HARBORS',
       'HARBR', 'HAVEN', 'HBR', 'HBRS', 'HEIGHTS', 'HIGHWAY', 'HIGHWY', 'HILL', 'HILLS', 'HIWAY', 'HIWY', 'HL', 'HLLW',
       'HLS', 'HOLLOW', 'HOLLOWS', 'HOLW', 'HOLWS', 'HRBOR', 'HT', 'HTS', 'HVN', 'HWAY', 'HWY', 'INLET', 'INLT', 'IS',
       'ISLAND', 'ISLANDS', 'ISLE', 'ISLES', 'ISLND', 'ISLNDS', 'ISS', 'JCT', 'JCTION', 'JCTN', 'JCTNS', 'JCTS',
       'JUNCTION', 'JUNCTIONS', 'JUNCTN', 'JUNCTON', 'KEY', 'KEYS', 'KNL', 'KNLS', 'KNOL', 'KNOLL', 'KNOLLS', 'KY',
       'KYS', 'LAKE', 'LAKES', 'LAND', 'LANDING', 'LANE', 'LCK', 'LCKS', 'LDG', 'LDGE', 'LF', 'LGT', 'LGTS', 'LIGHT',
       'LIGHTS', 'LK', 'LKS', 'LN', 'LNDG', 'LNDNG', 'LOAF', 'LOCK', 'LOCKS', 'LODG', 'LODGE', 'LOOP', 'LOOPS', 'MALL',
       'MANOR', 'MANORS', 'MDW', 'MDWS', 'MEADOW', 'MEADOWS', 'MEDOWS', 'MEWS', 'MILL', 'MILLS', 'MISSION', 'MISSN',
       'ML', 'MLS', 'MNR', 'MNRS', 'MNT', 'MNTAIN', 'MNTN', 'MNTNS', 'MOTORWAY', 'MOUNT', 'MOUNTAIN', 'MOUNTAINS',
       'MOUNTIN', 'MSN', 'MSSN', 'MT', 'MTIN', 'MTN', 'MTNS', 'MTWY', 'NCK', 'NECK', 'OPAS', 'ORCH', 'ORCHARD',
       'ORCHRD', 'OVAL', 'OVERPASS', 'OVL', 'PARK', 'PARKS', 'PARKWAY', 'PARKWAYS', 'PARKWY', 'PASS', 'PASSAGE', 'PATH',
       'PATHS', 'PIKE', 'PIKES', 'PINE', 'PINES', 'PKWAY', 'PKWY', 'PKWYS', 'PKY', 'PL', 'PLACE', 'PLAIN', 'PLAINS',
       'PLAZA', 'PLN', 'PLNS', 'PLZ', 'PLZA', 'PNE', 'PNES', 'POINT', 'POINTS', 'PORT', 'PORTS', 'PR', 'PRAIRIE', 'PRK',
       'PRR', 'PRT', 'PRTS', 'PSGE', 'PT', 'PTS', 'RAD', 'RADIAL', 'RADIEL', 'RADL', 'RAMP', 'RANCH', 'RANCHES',
       'RAPID', 'RAPIDS', 'RD', 'RDG', 'RDGE', 'RDGS', 'RDS', 'REST', 'RIDGE', 'RIDGES', 'RIV', 'RIVER', 'RIVR', 'RNCH',
       'RNCHS', 'ROAD', 'ROADS', 'ROUTE', 'ROW', 'RPD', 'RPDS', 'RST', 'RTE', 'RUE', 'RUN', 'RVR', 'SHL', 'SHLS',
       'SHOAL', 'SHOALS', 'SHOAR', 'SHOARS', 'SHORE', 'SHORES', 'SHR', 'SHRS', 'SKWY', 'SKYWAY', 'SMT', 'SPG', 'SPGS',
       'SPNG', 'SPNGS', 'SPRING', 'SPRINGS', 'SPRNG', 'SPRNGS', 'SPUR', 'SPURS', 'SQ', 'SQR', 'SQRE', 'SQRS', 'SQS',
       'SQU', 'SQUARE', 'SQUARES', 'ST', 'STA', 'STATION', 'STATN', 'STN', 'STR', 'STRA', 'STRAV', 'STRAVEN',
       'STRAVENUE', 'STRAVN', 'STREAM', 'STREET', 'STREETS', 'STREME', 'STRM', 'STRT', 'STRVN', 'STRVNUE', 'STS',
       'SUMIT', 'SUMITT', 'SUMMIT', 'TER', 'TERR', 'TERRACE', 'THROUGHWAY', 'TPKE', 'TRACE', 'TRACES', 'TRACK',
       'TRACKS', 'TRAFFICWAY', 'TRAIL', 'TRAILER', 'TRAILS', 'TRAK', 'TRCE', 'TRFY', 'TRK', 'TRKS', 'TRL', 'TRLR',
       'TRLRS', 'TRLS', 'TRNPK', 'TRWY', 'TUNEL', 'TUNL', 'TUNLS', 'TUNNEL', 'TUNNELS', 'TUNNL', 'TURNPIKE', 'TURNPK',
       'UN', 'UNDERPASS', 'UNION', 'UNIONS', 'UNS', 'UPAS', 'VALLEY', 'VALLEYS', 'VALLY', 'VDCT', 'VIA', 'VIADCT',
       'VIADUCT', 'VIEW', 'VIEWS', 'VILL', 'VILLAG', 'VILLAGE', 'VILLAGES', 'VILLE', 'VILLG', 'VILLIAGE', 'VIS', 'VIST',
       'VISTA', 'VL', 'VLG', 'VLGS', 'VLLY', 'VLY', 'VLYS', 'VST', 'VSTA', 'VW', 'VWS', 'WALK', 'WALKS', 'WALL', 'WAY',
       'WAYS', 'WELL', 'WELLS', 'WL', 'WLS', 'WY', 'XING', 'XRD', 'XRDS']

states = ['A.S.', 'AK', 'AK.', 'AL', 'ALA.', 'ALABAMA', 'ALASKA', 'AMERICAN SAMOA', 'AR', 'ARIZ.', 'ARIZONA', 'ARK.',
          'ARKANSAS', 'AS', 'AZ', 'CA', 'CAL.', 'CALIF.', 'CALIFORNIA', 'CF', 'CL', 'CM', 'CNMI', 'CO', 'COLO.',
          'COLORADO', 'CONN.', 'CONNECTICUT', 'CT', 'D.C.', 'DC', 'DE', 'DEL.', 'DELAWARE', 'DIS. COL.',
          'DISTRICT OF COLUMBIA', 'DL', 'FL', 'FLA.', 'FLORIDA', 'GA', 'GA.', 'GEO.', 'GEORGIA', 'GU', 'GUAM',
          'GUMMP', 'HA', 'HAW.', 'HAWAII', 'HI', 'HI.;', 'IA', 'ID', 'IDA.', 'IDAHO', 'IL', 'ILL.', 'ILLINOIS',
          'IN', 'IND.', 'INDIANA', 'IOA.', 'IOWA', 'KA', 'KA.', 'KAN.', 'KANS.', 'KANSAS', 'KEN.', 'KENT.', 'KENTUCKY',
          'KS', 'KY', 'KY.', 'LA', 'LA.', 'LOUISIANA', 'M.P.', 'MA', 'MAINE', 'MAR.', 'MARY.', 'MARYLAND', 'MASS.',
          'MASSACHUSETTS', 'MC', 'MD', 'MD.', 'ME', 'MI', 'MICH.', 'MICHIGAN', 'MINN.', 'MINNESOTA', 'MISS.',
          'MISSISSIPPI', 'MISSOURI', 'MN', 'MNPPR', 'MO', 'MO.', 'MONT.', 'MONTANA', 'MP', 'MS', 'MT', 'N. CAR.',
          'N. DAK.', 'N. JERSEY', 'N. MEX.', 'N. YORK', 'N.C.', 'N.D.', 'N.H.', 'N.J.', 'N.M.', 'N.Y.', 'NB', 'NC',
          'ND', 'NE', 'NEB.', 'NEBR.', 'NEBRASKA', 'NEV.', 'NEVADA', 'NEW HAMPSHIRE', 'NEW JERSEY', 'NEW M.',
          'NEW MEX.', 'NEW MEXICO', 'NEW YORK', 'NH', 'NJ', 'NM', 'NORTH CAROLINA', 'NORTH DAKOTA',
          'NORTHERN MARIANA ISLANDS', 'NV', 'NY', 'O.', 'OH', 'OH.', 'OHIO', 'OK', 'OKLA.', 'OKLAHOMA', 'OR', 'ORE.',
          'OREG.', 'OREGON', 'P.R.', 'PA', 'PA.', 'PENN.', 'PENNA.', 'PENNSYLVANIA', 'PR', 'PUERTO RICO', 'R.I.',
          'R.I. & P.P.', 'RHODE ISLAND', 'RI', 'S. CAR.', 'S. DAK.', 'S.C.', 'S.D.', 'SC', 'SD', 'SODAK',
          'SOUTH CAROLINA', 'SOUTH DAKOTA', 'TENN.', 'TENNESSEE', 'TEX.', 'TEXAS', 'TN', 'TX', 'U.S. VIRGIN ISLANDS',
          'U.S.V.I.', 'UT', 'UT.', 'UTAH', 'V.I.', 'VA', 'VA.', 'VERM.', 'VERMONT', 'VI', 'VIR', 'VIRG.', 'VIRGINIA',
          'VT', 'VT.', 'W. VA.', 'W. VIRG.', 'W.V.', 'W.VA.', 'WA', 'WASH.', 'WASHINGTON', 'WEST VIRGINIA', 'WI',
          'WIS.', 'WISC.', 'WISCONSIN', 'WN', 'WN.', 'WS', 'WV', 'WY', 'WYO.', 'WYOMING']
